if(EXISTS "/Users/sujaykonda/Downloads/crypto_hft/build_storage/test_storage[1]_tests.cmake")
  include("/Users/sujaykonda/Downloads/crypto_hft/build_storage/test_storage[1]_tests.cmake")
else()
  add_test(test_storage_NOT_BUILT test_storage_NOT_BUILT)
endif()
